<?php

namespace ContainerVgz7bPf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalendarControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'CalendarBundle\Controller\CalendarController' shared autowired service.
     *
     * @return \CalendarBundle\Controller\CalendarController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/tattali/calendar-bundle/src/Controller/CalendarController.php';
        include_once \dirname(__DIR__, 4).'/vendor/tattali/calendar-bundle/src/Serializer/SerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/tattali/calendar-bundle/src/Serializer/Serializer.php';

        return $container->services['CalendarBundle\\Controller\\CalendarController'] = new \CalendarBundle\Controller\CalendarController(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), new \CalendarBundle\Serializer\Serializer());
    }
}
