<?php

namespace ContainerFIlxSEW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NPIWXp3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nPIWXp3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nPIWXp3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'calendar' => ['privates', '.errored..service_locator.nPIWXp3.App\\Entity\\Conges', NULL, 'Cannot autowire service ".service_locator.nPIWXp3": it references class "App\\Entity\\Conges" but no such service exists.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'calendar' => 'App\\Entity\\Conges',
            'doctrine' => '?',
        ]);
    }
}
