<?php

namespace ContainerFIlxSEW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCongesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nPIWXp3.App\Entity\Conges' shared service.
     *
     * @return \App\Entity\Conges
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nPIWXp3": it references class "App\\Entity\\Conges" but no such service exists.');
    }
}
