<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTIw4TpV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTIw4TpV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTIw4TpV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTIw4TpV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTIw4TpV\App_KernelDevDebugContainer([
    'container.build_hash' => 'TIw4TpV',
    'container.build_id' => '5583074d',
    'container.build_time' => 1654033976,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTIw4TpV');
