<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT9ivLey\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT9ivLey/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT9ivLey.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT9ivLey\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT9ivLey\App_KernelDevDebugContainer([
    'container.build_hash' => 'T9ivLey',
    'container.build_id' => 'b8c72ea5',
    'container.build_time' => 1654514264,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT9ivLey');
