<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4DxRym1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4DxRym1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4DxRym1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4DxRym1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4DxRym1\App_KernelDevDebugContainer([
    'container.build_hash' => '4DxRym1',
    'container.build_id' => '5f65431c',
    'container.build_time' => 1654295059,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4DxRym1');
